name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run build
          npm run docs
          cp -r devdocs demos/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo # The branch the action should deploy to.
          folder: demos # The folder the action should deploy.
